language: java

stages:
- name: DEV Validation
	if: type = pull_request AND branch == "dev"

	- name: MERGE Validation
	if: type = pull_request and branch == "merge"

jobs:
	include:
		- stage: DEV Validation
			script: 
			  - echo "validating against DEV"
			  - ant -buildfile build.xml validateNoTest 
			    -Dsfdc.deployFile=package.xml
			    -Dsfdc.username=$SFDC_DEV_USERNAME
			    -Dsfdc.password=$SFDC_DEV_PASSWORD
			    -Dsfdc.serverUrl=$SFDC_TEST_URL			

		- stage: MERGE Validation
			script: 
			  - echo "validating against MERGE"
			  - ant -buildfile build.xml validateNoTest 
			    -Dsfdc.deployFile=package.xml
			    -Dsfdc.username=$SFDC_DEV_USERNAME
			    -Dsfdc.password=$SFDC_DEV_PASSWORD
			    -Dsfdc.serverUrl=$SFDC_TEST_URL

