language: java
conditions: v1

stages:
  - name: DEV Validation
    if: type = pull_request AND branch == "dev"
  
  - name: MERGE Validation
    if: type = pull_request and branch == "merge"

jobs:
  include:
    - stage: DEV Validation
      script:
        ant -buildfile build.xml validateNoTest 
          -Dsfdc.deployFile=package.xml
          -Dsfdc.username=$SFDC_DEV_USERNAME
          -Dsfdc.password=$SFDC_DEV_PASSWORD
          -Dsfdc.serverUrl=$SFDC_TEST_URL			

    - stage: MERGE Validation
      script: 
        - ant -buildfile build.xml validateNoTest 
          -Dsfdc.deployFile=package.xml
          -Dsfdc.username=$SFDC_DEV_USERNAME
          -Dsfdc.password=$SFDC_DEV_PASSWORD
          -Dsfdc.serverUrl=$SFDC_TEST_URL

